### ISSUE TITLE
FTDI Chip Drivers

### ISSUE THREAD

**Issue by RyanHope** [pbatard/libwdi#137]
I have a commercial windows app that communicates with a FTDI usb serial adapter that relies on the following drivers (http://www.ftdichip.com/FTDrivers.htm). I am also developing a cross-platform app that uses this same adapter. My cross-platform app works great with libusbK, but none of the drivers in Zdiag (which uses this lib I believe) will restore my system back to state where I can easily switch back to the commercial app. The only way to get the commercial app to work is to go into device manager and delete the libusbK device and files manually. Think you could somehow support these drivers?

**Comment by pbatard** [comment]
I'm afraid I have no plans to add manufacturer specific drivers, especially as the demand for FTDI drivers, which target a specific set of devices, is going to be a lot more limited than the demand for __generic__ USB drivers, which is what WinUSB, libusb0 and libusbK provide.

If I were to do what you request, that would open the door to anyone who uses any kind of USB device to ask that I add their custom driver to Zadig (because why should I give you what you want and not them!), and it would quickly become unmanageable, so I hope you can understand where I am coming from.

You can however use the libwdi source to develop your custom version of Zadig that embeds the drivers you want.
