### ISSUE TITLE
Issue with Win7->win10 upgrade

### ISSUE THREAD

**Issue by karel-3d** [pbatard/libwdi#146]
We have a strange issue with one customer

We install winusb driver with wdi-simple in our installer on windows 7, but not on windows 10.

One of our users now installed libwdi driver on windows 7 and used the device (so windows has remembered the device). Then he updated Windows to Windows 10 and device stopped working.

Do you know what can be the issue here?

I do not have more data yet and I don't know if I can replicate it; I will install a VM and try to replicate it with both wdi-simple and zadig and tell results here

Anyway, before I do it (since it will be painful), do you have any idea if it's an issue of libwdi or some issue of the computer? (or something in between)

Should driver installed with libwdi and the installed devices using the driver "survive" win7->win10 upgrade?

**Comment by pbatard** [comment]
Make sure the customer has a look at the various `setupapi.###.log` in `C:\Windows\Inf\`. It might explain what's going on.

Also, in later versions of Windows, there are driver priorities assigned by Microsoft according to whether the driver comes from Windows Update, and other factors. This may result in an installed driver, installed by libwdi, being "overruled" by a preferred driver with a higher score.

Also, if you are using a WCID driver, be mindful that if a manufacturer has created a poorly written driver that uses the `MS_COMP_WINUSB` ID (for instance HP have been known to do that), instead of letting Windows itself handle the driver installation, you may get the libwdi driver being overwritten (see #131).

Anyway, I'm afraid you will have to dig into the registry and Windows logs to try to figure out why the libwdi driver is no longer working.

**Comment by karel-3d** [comment]
OK. I will update this thread. I just asked if it's not some well-known issue. (Usually winusb devices work flawlessly on win10, without need for this library.)

**Comment by pbatard** [comment]
No update &rarr; Closed
