### ISSUE TITLE
Zadig wont recognize my switch's drivers

### ISSUE THREAD

**Issue by AsianShrek** [pbatard/libwdi#151]
Hi. As the title says, Zadig can not see my switch's driver. I have tried everything to solve it. Still nothing.

**Comment by pbatard** [comment]
I think you are mistaken.

Zadig does not have to "recognize" drivers. Zadig __installs__ drivers.

I will therefore assume that your issue is that Zadig can not see your __hardware device__ (is it a switch?) which is a very different thing from a driver (which is software, not hardware).

If that is the case, have you tried _Options_ &rarr; _List All Devices_?

If that still doesn't work, you will need to send your full log (_Options_ &rarr; _Advanced Mode_) and indicate the type of device you are trying to access and whether you can see it __as an USB device__ in Windows Device Manager.
