### ISSUE TITLE
Update all Wiki links

### ISSUE THREAD

**Issue by E3V3A** [pbatard/libwdi#153]
Most links to MS sites are broken. Please update the links.

**Comment by pbatard** [comment]
The Wiki is open to every GitHub users for edition. If you found some broken links, can you please update them? Remember that Open Source is usually a collaborative effort...

**Comment by E3V3A** [comment]
I know and usually do, but in this case I am so new to using this project that I am not able to guess what to look for in any new links that would replace what was there.

**Comment by pbatard** [comment]
Well, can you at least point to the links that you have found to be broken. Clearly, if you have reported this issue, it's because you have this data, and providing this is will be a lot more helpful than waiting for a developer, who is busy on many other things, to manage to find some time to try to figure out where exactly are these links that you say are broken. Again, collaborative effort. Thank you.

**Comment by Mihaylov93** [comment]
I updated some of the Microsoft broken links. 

Here is the list of the updated links:
```
Determining Whether a Device Is Plugged In and removal of phantom devices
Writing a Device Installation Application
Determining Whether a Device Is Plugged In and removal of phantom devices
Troubleshooting Device Installation with the SetupAPI Log File
```

**Comment by pbatard** [comment]
Links have been updated. Closing.
