### ISSUE TITLE
Windows 10 1903 WCID Error

### ISSUE THREAD

**Issue by danieltellezp** [pbatard/libwdi#162]
![Error Driver](https://user-images.githubusercontent.com/41880878/61012564-a30aac00-a344-11e9-9940-418daa4382d5.png)

The driver not working in Windows 10 1903.

**Comment by pbatard** [comment]
The `X` near WCID does not indicate an issue. It simply means that the device you are using is not WCID compliant.

If the Nitendo Swicth was WCID compliant, you wouldn't actually need to use Zadig at all, as WinUSB would automatically be installed.

You can read more about WCID [here]](https://github.com/pbatard/libwdi/wiki/WCID-Devices).

Since I believe I have answered your concern, I will close this issue.
