### ISSUE TITLE
Example of how to use libwdi to install a generic device driver using provided inf/sys

### ISSUE THREAD

**Issue by trollcop** [pbatard/libwdi#181]
Is there a code example of how to use libwdi to successfully install a device (ex. USB device for WinUSB) by using unmodified inf/sys/dll files?

I've looked at the zadig/wdi examples and there's embedded_files.h which is hardcoded to add WinUSB, libusb, etc stuff, what if I already have a normal driver consisting of inf/sys file and don't want to modify it in any way but just install it programmatically?

I've looked at the USER_FILE option in zadig configuration but that still seems buggy and requires extra tokens in the .inf.in file and such.

Is there an example that shows how to do this for a generic driver?

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/Install#Using_a_custom_driver_file_with_libwdi

I did add some provision to set a `USER_DIR` variable to point to a location containing driver files that you can embed (see https://github.com/pbatard/libwdi/blob/master/msvc/config.h#L46-L49, or, if compiling with MinGW, you can try to use `--with-userdir`), and then you __should__ be able to use `` with [`wdi_prepare_driver()`](https://github.com/pbatard/libwdi/wiki/Usage#struct_wdi_options_prepare_driver) to select that driver for installation, but I haven't really tested it.

It shouldn't require extra tokens in the `inf` file, since you're not going to modify the driver (which means that your VID:PID can only be fixed, as if they aren't then you're not going to use _unmodified inf/sys/dll files_).

I'm afraid there's only so much help I can provide with libwdi usage, and you'll have to fill the rest on your own.
