### ISSUE TITLE
After install zading，system printer not work。

### ISSUE THREAD

**Issue by rodchen-king** [pbatard/libwdi#220]
we build pos with escpos-usb npm package。It need install zading。
After install zading。 printer work fine in pos system。

![image](https://user-images.githubusercontent.com/19780441/125244450-f0e69000-e321-11eb-8edb-d2e1242d8932.png)

but I found computer printer not work。How to deal with it？

![image](https://user-images.githubusercontent.com/19780441/125244292-bc72d400-e321-11eb-9c43-d3a53eab4f65.png)

**Comment by pbatard** [comment]
Zadig installs the WinUSB driver for pos. The WinUSB driver is __not__ compatible with Windows native printing.

This means that you can't have both pos and Windows printing work at the same time. It can only be one or the other.

If you want to restore Windows printing, you need to uninstall the WinUSB driver and let Windows restore the default printer driver. But then you won't be able to use pos.

Note that this has nothing to do with Zadig, as the WinUSB driver comes from Microsoft (it's not something I or someone else developed, Microsoft did) and it's features and limitations are due to Microsoft's design. So there is nothing I can do in Zadig/libwdi to address your problem. If you want to use software that relies on WinUSB to access a device, then you need to be aware that other software, including Windows, may no longer be able to access that device.

**Comment by rodchen-king** [comment]
> Zadig installs the WinUSB driver for pos. The WinUSB driver is **not** compatible with Windows native printing.
> 
> This means that you can't have both pos and Windows printing work at the same time. It can only be one or the other.
> 
> If you want to restore Windows printing, you need to uninstall the WinUSB driver and let Windows restore the default printer driver. But then you won't be able to use pos.
> 
> Note that this has nothing to do with Zadig, as the WinUSB driver comes from Microsoft (it's not something I or someone else developed, Microsoft did) and it's features and limitations are due to Microsoft's design. So there is nothing I can do in Zadig/libwdi to address your problem. If you want to use software that relies on WinUSB to access a device, then you need to be aware that other software, including Windows, may no longer be able to access that device.

How to uninstall the WinUSB?

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it
