### ISSUE TITLE
I updated my switch to firmware version 11 and now it wont start.

### ISSUE THREAD

**Issue by Alecampo86** [pbatard/libwdi#223]
I tried using Zadig and reinstalling  libusbK (v3.0.7.0) drivers as I would usually do in these ocations, but this time it wont start. Screen is lightend but black.

**Comment by pbatard** [comment]
That has nothing to do with libwdi.

All libwdi did was install the Microsoft WinUSB driver that allowed you to use __additional__ third party software (that I have no involvement with) through which you did whatever you did with you Swicth console.

You will need to ask your question elsewhere, because your question has nothing to do with using libwdi or one of the USB drivers that libwdi can install. If anything, the fact that you were able to update your switch firmware means that the driver was installed successfully, which means that, as far as libwdi is concerned, there is no issue to address.
