### ISSUE TITLE
How do I run this on linux

### ISSUE THREAD

**Issue by rodude123** [pbatard/libwdi#246]
The wiki is really great and comprehensive but I found nothing on there on how to run this on Linux?

**Comment by pbatard** [comment]
Please bear in mind that the 'W' in libwdi stands for __Windows__ (_Windows Driver Installer library_), and the only purpose of this library is to install __Windows__ drivers such as WinUSB, `libusb0.sys` or `libusbk.sys`.

I'm not sure what use you think it would have on Linux, but I can tell you that, in practice, it would have absolutely none, since WinUSB, libusb0 and libusbK can not and will never work on Linux.

Therefore, since it makes absolutely no sense to run this on Linux, running it on Linux is not supported, even if, as it happens, we use Makefiles and a build process that is commonly found on (__but NOT exclusive to__!!) Linux.

This is Windows only. It requires a Windows platform, both for building and for running.
