### ISSUE TITLE
Zadig failure

### ISSUE THREAD

**Issue by stz9** [pbatard/libwdi#255]
Hi,
I'm trying to use the latest zadig-2-7.exe to install the WinUSB on window 10,
after selection of "install driver" button, I get "The driver Installation failed" message box 

downloading + compiling the source code (VS2019 +  comment the xxx_DIR in the config.h)
gives other error message :  (after a few sec of "installing driver bar") : "driver installation cancelled by user"
looking in the debugger gives , that this error code is came from process_message()
case IC_SET_STATUS: : return (int)buffer[1]; // WDI_ERROR_USER_CANCEL = -14,

Attached is the log

Do you have any idea ?

Best Regards,

Shl

[log.txt](https://github.com/pbatard/libwdi/files/8169732/log.txt)

**Comment by pbatard** [comment]
Please post the __FULL LOG__ of how you installed the driver from Zadig. It should tell you very explicitly what the underlying issue is.

In Zadig: _Options_ &rarr; _Advanced Mode_ and then run a driver install.

I cannot help you unless you provide a full log.

**Comment by stz9** [comment]
Please find the attached zadig.log file

Thanks

[Zadig.log](https://github.com/pbatard/libwdi/files/8178484/Zadig.log)


[Zadig.log](https://github.com/pbatard/libwdi/files/8178498/Zadig.log)

**Comment by pbatard** [comment]
> `Zadig 2.6.754`

You are using an old version of Zadig and are getting the following `libwdi:warning [CreateSelfSignedCert] Could not obtain a key container: Invalid parameter` which is the root of your issue. Please try with the latest, as it may provide more information about your issue, which is an environmental problem (i.e. something that you only get if you altered your Windows configuration from a vanilla Windows installation).

**Comment by stz9** [comment]
Hello,
The problem exist also in the latest code.
Please find the attached log file of the latest master code (Zadig 2.7.768)
[Zadig.log](https://github.com/pbatard/libwdi/files/8192233/Zadig.log)

Best Regards

**Comment by pbatard** [comment]
Again, I'm afraid that your issue is an environmental problem (i.e. something that you only get if you altered your Windows configuration from a vanilla Windows installation).

The problem is that you are getting this error `[CreateSelfSignedCert] Could not obtain a key container: Object already exists. (0x8009000F)`, which users of a standard Windows installation do not get, so that means that your PKI policies have been altered in some way, in a manner that prevents Zadig from working.

At the moment, I'm afraid I have no idea what Windows policy changes can be the cause of this issue, so it will be up to you to identify what they are, and reopen the issue once you have found what Windows setting (possibly a local group policy, but it may be something else) is responsible for this.

If you test on a standard Windows installation (i.e. a version of Windows that was freshly installed and on which the settings have not been modified from the defaults) you should find that this issue does not occur, so there is really not much I can do until you have identified the manner in which your Windows platform was modified from the standard installation.
