### ISSUE TITLE
Hack RF-One Amp Disabled (Any Ideas?)

### ISSUE THREAD

**Issue by BrendaEM** [pbatard/libwdi#262]
Hi,

With Zadiag 2.7, and SDR-Sharp the amplifier settings are grayed out. I tried several reinstalls. The issue is also with the community release of SDR-Sharp.

I do not believe the unit is damaged, as it did work before, and it was never connected directly.

The amplification, on a Hack RF-One was very useful.
Any help would be appreciated. If not here, then where?

AGC is not only disabled, but also grayed out.

![image](https://user-images.githubusercontent.com/20957198/172714606-b4e1b089-6bf9-4553-9928-9f6e990696fe.png)

**Comment by pbatard** [comment]
> If not here

Clearly not here since there hasn't been any reply to your post, which makes sense, since libwdi is not a SDR-Sharp (or any specific device really) oriented library, but a __generic__ library, that is completely agnostic to the device you are using.

> then where?

SDR-Sharp user forums should be a good place to start, which this certainly isn't.

Asking here is like asking Microsoft for Adobe PhotoShop support, because PhotoShop happens to run on Windows. Obviously, you're not going to the get answer you're looking for.

&rarr; Closing.
