### ISSUE TITLE
Add support for new project libusb

### ISSUE THREAD

**Issue by LucienMP** [pbatard/libwdi#266]
Would it be possible to add support for libusb which replaces the now fix-only older lib-usb
See the new project for [libusb](https://libusb.info/) and its [github](https://github.com/libusb/libusb)

**Comment by pbatard** [comment]
I don't think you quite understand what this project is about. It is only about installing a __driver__, whereas libusb is a __library__.

I think you are being confused with the fact that libusb0 and libusbK are libraries that provided their own custom driver, so we include support for them, whereas libusb is designed to work primarily __not__ with it's own custom driver, but with Microsoft's WinUSB, which is what this project installs.

For reference, because I was the main developer of the libusb WinUSB backend (as well as one of the people behind the creation of the libusb website which you link to), I can tell you that I developed Zadig precisely with the goal of making it easier to use libusb, so if there was something that libwdi did not do to help with libusb usage, it would long have been done.
