### ISSUE TITLE
Undocumented and unexpected restrictions on format of external INI file due to broken tokenizing code

### ISSUE THREAD

**Issue by codygray** [pbatard/libwdi#267]
At the time of this writing, the [latest release, v1.4.1,](https://github.com/pbatard/libwdi/releases/tag/v1.4.1) of libwdi [adds a new `external_inf` option to `wdi_options_prepare_driver` to allow the use of an external INF file instead of the embedded one](https://github.com/pbatard/libwdi/pull/234). This is a fantastic feature. However, the implementation is flawed. The *only* way it works is if the external INF file is encoded as UTF-8 *and* uses \*nix-style line breaks (`LF` only). Otherwise, the code in `libwdi.c` (specifically, the `wdi_tokenize_file` function) fails to read INF file. These requirements are extremely unexpected, non-obvious, and not documented anywhere.

Obviously, on Windows, text files (including \*.INF files) are expected to use Windows-style line breaks (`CR`+`LF`), not \*nix-style line breaks. While it is possible to convert a standard \*.INF file to have \*nix-style line breaks, this takes extra effort and makes the \*.INF file unreadable by Windows itself and in standard Windows applications, like Notepad.

And, again, obviously, on Windows, text files (including \*.INF files) use the UTF-16 LE encoding. This is what Notepad (and, indeed, Windows itself) has traditionally referred to simply as "Unicode", since this is what Windows has been using as a Unicode encoding since before Unicode was standardized. It is rare that one finds text files on Windows that are in UTF-8 format, and it is *especially* rare that one finds system-generated and/or -input files that are in UTF-8 format, because this is not a standard format for the platform. (The way libwdi uses UTF-8 throughout, despite this making it incompatible in nearly every way with Windows itself, is, in my opinion, a poor design practice, especially considering that libwdi is inherently Windows-specific, with notable performance penalties—every call to an `A`-suffixed WinAPI function is doing a conversion from MBCS to UTF-16 internally and then dispatching to the corresponding `W`-suffixed WinAPI function—and an *extremely* poor implementation, but even putting that opinion aside, good software is liberal in what it accepts, so it certainly should accept input files in UTF-16 format, even if it decides to convert them into something else for its internal use.)

Not to mention the \*.INF file that libwdi itself generates when *not* using the `external_inf` option violates *both* of these requirements: the file uses the UTF-16 LE encoding *and* uses Windows-style line breaks, exactly as Windows itself expects and, thus, as libwdi should do.

So, the simple solution (to document these requirements for external \*.INF files) is the *wrong* solution. **The *correct* solution is to properly handle external \*.INF files in the normal, expected Windows format, the same format otherwise used by libwdi for generated \*.INF files**.

The reason that `wdi_tokenize_file` is unable to handle Windows-style line breaks is because it opens the file in text mode (with the call to `fopen` passing only `"r"` as the option), retrieves the file size in bytes (using the `fseek`, `ftell`, and `fseek`/`rewind` idiom), reads the file's contents using `fread`, and then verifies that the number of bytes read by `fread` matches the number of bytes in the file. The problem is, the number of bytes read by `fread` *won't match*, since the file is opened in text mode and `fread` on Windows converts the `\r\n` line breaks in the file into `\n` when it reads them. Thus, the number of bytes returned by `fread` is less than the number of bytes actually in the file by exactly one-half the number of line breaks in the file. This feeble byte-count "validation" should either be removed entirely, or, if you want to validate the file in terms of bytes, you should open, read, and write it in *binary* mode (not text mode) so that you can handle the raw bytes yourself.

The reason why `wdi_tokenize_file` is unable to handle UTF-16–encoded files is similar. To properly handle Unicode on Windows, you should be using the wide-character variants of the standard library functions, which can handle all possible encodings: UTF-16 (the standard), UTF-8, and ASCII. If you don't want to do that, you need to open the files in binary mode and deal with the bytes yourself, not let the standard library functions do any sort of automatic text processing (e.g., to munge line breaks) or to get yourself in a position where code units are broken up.

libwdi's questionable design decision not to use the standard Windows format for text encoding makes fixing this far more difficult and fiddly than it should be, not to mention virtually guarantees that there will always be issues and edge-cases arising from the processing of any externally-sourced input files. If you want to handle input files encoded as UTF-16, UTF-8, and ASCII (the *bare minimum*; ideally, the "ANSI" encoding matching the configured character set encoding would also be supported), you have little choice but to implement all sorts of complicated heuristics and BOM detection. If it were me, I'd open and manipulate the file using the wide-character functions, and then convert it to your desired encoding after all loading, parsing, and tokenization. But, regardless of which approach you choose to take, this absolutely must be fixed, as it's a serious usability problem that causes libwdi's `external_inf` option unable to process even the exact same \*.INF file that libwdi itself generates on a previous run without the `external_inf` option.

**Comment by pbatard** [comment]
> At the time of this writing, the latest release, v1.4.1 of libwdi adds a new `external_inf` option to `wdi_options_prepare_driver` to allow the use of an external INF file instead of the embedded one

Just like everything else, this feature is provided 'AS IS', and comes directly from the fact that someone provided a patch, rather than us purposefully designing libwdi to provide such a feature.

Please read the explicit terms of the license under which libwdi is provided.

> libwdi's questionable design decision not to use the standard Windows format for text encoding

This is not a design decision. This comes from libdwi __not__ being a project I can invest a lot of time on, and therefore relying on other people's work for elements (such as supporting external inf).

Let me be 100% clear on this: libwdi is a __very low priority project__ for me at this stage, so the less time I spend on it the better. And since (gasp) I don't really care about external inf support, because this was never designed as a prime feature of libwdi, I will continue to rely on the support of __others__ who do care about it to improve of fix what I consider to be minor issues, such as having to convert the inf to CRLF. __OR__, if it turns out that supporting that feature becomes a headache (such as getting issues opened to pretty much berate me about how unacceptable it is for libwdi to provide a minor feature with a slight drawback), I will remove it altogether, because, again, I don't really care about it, and it was provided 'AS IS' in the hope that it could help a small section of libwdi users.

> this absolutely must be fixed

I'll wait for your or somebody else's patch then. Again, the library is free. My time __isn't__ and, for a minor feature that was added as a bonus for a very limited number of feature, and not something I see as a prime feature (because IMO, the people who are using it are more than likely trying to avoid writing their own driver package, __as they should instead of relying in a free library to do that for them__), I'm not planning to do more than add a note in the Wiki that documents the fact that you need to make sure your inf is UTF-8 (which quite frankly, every text file should default too in 2022) and using LF's.

Closed as: I don't care enough about this feature to take time away from my other projects, especially if people reporting on it are low key implying that I'm doing a bad job with something that is not a core feature of libwdi and therefore is very much provided _"'AS IS', without warranty of any kind, either expressed or implied, including (...) the implied warrant(y) of fitness for __YOUR__ particular purpose"_
