### ISSUE TITLE
Updating Vendor IDs and Vendor Names

### ISSUE THREAD

**Issue by sresam89** [pbatard/libwdi#271]
There a bunch of vendor Ids and names that need to be updated from www.linux-usb.org

Is there a way to update the Vendor string in inf-file without compiling the software 

I can request a PR if needed, to update "vid_data.c"?

**Comment by pbatard** [comment]
> Is there a way to update the Vendor string in inf-file without compiling the software

No. I usually only update it when I release a new version of Zadig.

> I can request a PR if needed, to update "vid_data.c"?

Can you describe why you absolutely need the vendor IDs updated, considering that I am not planning to produce a release of libwdi or Zadig even if we update that file, which means that, the only way it should matter to you is if you cloned the git repo, which means that, since you're working on your own copy, you shouldn't really need to have an update upstream...

**Comment by sresam89** [comment]
I was wondering If I can use a local copy or should wait for an official release since its been an year since last release.
I was not sure if I can use dynamic binding for installing the drivers into my software package

**Comment by pbatard** [comment]
> I was wondering If I can use a local copy

If you think you need updated VIDs, then you should use a local copy.

> since its been an year since last release.

Yes, and I am not planning to increase the release cycle if it's just to update the VID database. Unless there are major issues to fix, this project will not see frequent releases, as it is mature enough to accomplish its goal of installing drivers and I'm way too busy with other projects to want to devote that much time to libwdi.

> I was not sure if I can use dynamic binding for installing the drivers into my software package

That's not something I can answer for you. You will just have to try.

I will close this issue now.
