### ISSUE TITLE
Is it will be GPLv3?

### ISSUE THREAD

**Issue by jdzyzh** [pbatard/libwdi#279]
libwdi is LGPLv3 or newer， but if somebody include  libusb-win32 by following config

msvc\config.h

/* embed libusb0 driver files from the following location */
#ifndef LIBUSB0_DIR
#define LIBUSB0_DIR "D:/libusb-win32"
#endif

while, libusb-win32 is GPLv3， then the wdi dll will becom GPLv3 or not?

**Comment by pbatard** [comment]
No. We do __NOT__ link with the code of any of these drivers at any moment (we extract their data, but we don't execute their content) so, as long as they are redistributable, which means we can embed them in a binary for redistribution, which is exactly what we do, the license they use is completely irrelevant.

So, no, the libwdi license is unaffected by the license being used by the driver, because we are never executing any code from these drivers in libwdi (even during installation, if there is driver init, it is invoked by the OS not us).
