### ISSUE TITLE
libwdi Zadig and libusb-win32 1.3.0.x release

### ISSUE THREAD

**Issue by mcuee** [pbatard/libwdi#301]
Somehow libwdi/Zadig can not detect the proper version number of [libusb-win32 1.3.0.0 snapshot release](https://github.com/mcuee/libusb-win32/releases/tag/snapshot_1.3.0.0). Strage.

There are no issues with libusb-win32 1.2.7.3 or 1.2.7.4.

![Screenshot 2023-10-10 185842](https://github.com/pbatard/libwdi/assets/1294740/e36952bf-6a48-4b5d-9cce-88ec171a8028)

**Comment by mcuee** [comment]
This is invalid. I believe it has been fixed in libusb-win32 git HEAD.
https://github.com/mcuee/libusb-win32/commit/241e2efc2963d9bc2672c37d40f9c9bfee6a2b99

**Comment by mcuee** [comment]
But it is still a bit strange how libwdi detect the libusb-win32 version. I thought it uses libusb0.sys and not libusb0.dll.

**Comment by mcuee** [comment]
I have to re-open this issue as it still exists with libusb-win32 1.3.0.1 release. So looks like libwdi can not recognize libusb-win32 1.3.0.x version.

@pbatard and @dontech
Please take a look. Thanks.

![Capture_libusbwin32](https://github.com/pbatard/libwdi/assets/1294740/39fc4fdd-e2eb-4caa-96c8-9e3f46bc4368)

**Comment by mcuee** [comment]
@dontech

Please help to see if you have the same issue or not. Thanks.

**Comment by pbatard** [comment]
@dontech, @mcuee,

Sorry for not having had a chance to look into this. The issue is open so I am planning to do so, but I'm afraid this is not a high priority.

Zadig is built from GitHub actions, so if you clone the project, you should be able to just run the actions script and get the VS2022 artifacts that contain a Zadig executable. Alternatively, you can take a look at https://github.com/pbatard/libwdi/wiki/Compiling-and-debugging-libwdi-or-Zadig which is are beginner level instructions on how to install Visual Studio to build Zadig.

**Comment by mcuee** [comment]
@dontech 

I use VS2022 and just edit `config.h` to point out to the right locations for my system.

Same issue if I use github action (which uses VS2022). You can checkout the following run.
https://github.com/mcuee/libwdi/actions/runs/7872857879

**Comment by mcuee** [comment]
The issue still exists with libusb-win32 1.3.0.2 release.
https://github.com/mcuee/libusb-win32/releases/tag/snapshot_1.3.0.2

**Comment by dontech** [comment]
![image](https://github.com/pbatard/libwdi/assets/5517911/86fe30fd-7fcb-457b-94f9-855c45014044)

**Comment by dontech** [comment]
I am pretty sure this is a libwdi/zadig problem. After rebuilding a few times i got this:

![image](https://github.com/pbatard/libwdi/assets/5517911/464fc68b-30c0-44ef-a0b0-f10d4910bac6)

**Comment by dontech** [comment]
OK I found out there are 2 problems:

1) libwdi has an obvious bug in "embedder_files.h". This causes Zadig/libwdi to use the "install-filter.exe" to get the version info instead of the real DLL it was supposed to use (the "reuse" entries point to a previous entry that is not the same).

2) libusb-win32 has another obvious bug that causes the install-filter.exe to not have any resources, which should have contained the version info. I will fix this in libusb-win32: https://github.com/mcuee/libusb-win32/issues/64

For libwdi I have added it to my existing pull request:

@pbatard Please pull this: https://github.com/pbatard/libwdi/pull/314

**Comment by dontech** [comment]
@pbatard I updated the workflows to match the latest libusb0, so we could get the ARM64 binaries

**Comment by mcuee** [comment]
> For libwdi I have added it to my existing pull request:
> 
> @pbatard Please pull this: #314

I can confirm that PR #314 fixes this issue.
* #314

**Comment by dontech** [comment]
Either this fixes it or the change in libusb0 should have fixed this. Can be closed now @mcuee
