### ISSUE TITLE
Cannot select any device on ZADIG 2.9

### ISSUE THREAD

**Issue by GCTechnology** [pbatard/libwdi#336]
https://github.com/user-attachments/assets/17f1dd48-6ad5-4caa-9446-e61a5f220643

As shown in the video, I cannot select any device in the 'Dropdown', it just jump to the first device of the list...
Strange problem.

**Comment by pbatard** [comment]
Most likely you have a device that produces constant system notifications (Note that even if you don't hear a sound, theses notifications can happen), thus permanently refreshing the list to the first device.

The device refresh code from Zadig is not that complicated, so something on your system must be sending device arrival or device removal messages (`WM_DEVICECHANGE`) which Zadig picks up, which leads it to refresh its list and reset device selection to the first one. You will need to find what device produces these messages and fix it, as it is clearly a pure environmental issue (otherwise, many, many people would report a similar problem).
