### ISSUE TITLE
Building wdi-simple without Debug Information

### ISSUE THREAD

**Issue by deanchester** [pbatard/libwdi#39]
I'm using the wdi-simple with an Inno Setup Script installer, and I have built the example using the Release configuration, however when it runs wdi-simple it says that MSVCR120D.dll is missing. I've got back to it being the Installer_x64 project wanting, yet I've been through the properties for the project and it doesn't build it with Debug information, so I am confused as to where this is coming from.

**Comment by anth-git** [comment]
I had the same problem, that I was struggled for several hours… I think there is some error in embedder code. It seems that it uses installer_(x86/x64).exe that was compiled at very first time, and further changes don't affect this at all. Since I first built it as a Debug, it used debug version of installer_(x86/x64).exe which requires MSVCR120D.dll.
Remedy is very simple, though. I just downloaded fresh copy of sources, and built straight away in Release mode, without touching Debug one.

**Comment by deanchester** [comment]
Thanks this has resolved my issue.
