### ISSUE TITLE
Incompatibility between v1.2.4 and v1.2.5 for wdi_simple from command line

### ISSUE THREAD

**Issue by Moutarde** [pbatard/libwdi#74]
Hi Pete,

I am using wdi_simple in my application's installer, so that it also installs the USB drivers I need. I launch wdi_simple.exe with the parameter --type to custom, because I use a custom driver.
I updated libwdi from v1.2.4 to v1.2.5, and this didn't work anymore. It took me a long time to figure out that --type 3 didn't correspond to "custom" anymore, but to "usbser", and that I had to use --type 4...
It's not really a bug, but the fact that this change was not documented at all in the changelog made it very difficult to detect the problem.

Keep up the good work!

Nicolas

**Comment by pbatard** [comment]
The change is documented if you use `wdi-simple --help`:
```
>wdi-simple --help

-n, --name <name>          set the device name
-f, --inf <name>           set the inf name
-m, --manufacturer <name>  set the manufacturer name
-v, --vid <id>             set the vendor ID (VID, use 0x prefix for hex)
-p, --pid <id>             set the product ID (PID, use 0x prefix for hex)
-i, --iid <id>             set the interface ID (MI)
-t, --type <driver_type>   set the driver to install
                           (0=WinUSB, 1=libusb-win32, 2=libusbK, 3=usbser, 4=custom)
-w, --wcid                 use a WCID driver instead of a device-specific
                           one (WinUSB, libusb-win32 or libusbK only)
    --filter               use the libusb-win32 filter driver (requires -t1)
-d, --dest <dir>           set the extraction directory
-x, --extract              extract files only (don't install)
-c, --cert <certname>      install certificate <certname> from the
                           embedded user files as a trusted publisher
    --stealth-cert         installs certificate above without prompting
-s, --silent               silent mode
-b, --progressbar=[HWND]   display a progress bar during install
                           an optional HWND can be specified
-o, --timeout              timeout (in millis) to wait for any pending installations
-l, --log                  set log level (0 = debug, 4 = none)
-h, --help                 display usage
```

As you can see, the `-t` switch indicates which number you should use for custom.

Also, please not that the ability of libwdi to be used with a custom driver is provided "AS IS" (well, to be fair, the whole library is provided "AS IS" as per its license, but the custom driver is even more so). Custom driver support was added because it was relatively simple to do so, but that doesn't mean I will go out of my way to document it, or even keep it stable.

Anyway, I'm glad to hear you managed to figure out what the problem was, and sorted it. I will therefore close the issue.
