### ISSUE TITLE
libwdi using libusb only

### ISSUE THREAD

**Issue by xaqq** [pbatard/libwdi#95]
Hello,

I am creating a new issue because that was asked in the issue I come from (#45).
However, I tend to agree with @eng-Robert that his issue was similar to #45.

His last code sample, when used, fixes the issue I encountered: that is, a failure to install the driver when using LIBUSB only (which means `LIBUSBK_DIR` was not defined).

I gathered a few log messages that may help show the issue:

```
libwdi:debug [syslog] !!!  sto:                Driver package references a missing external file 'C:\WINDOWS\system32#LK_DLL#'. Error = 0x00000002
libwdi:debug [syslog] !!!  sto:                Failed to retrieve driver package copy files. Error = 0x00000002
libwdi:debug [syslog] !!!  sto:                Failed to get driver package copy files. Error = 0x00000002, Filename = C:\Users\xaqq\AppData\Local\Temp{a9dae95f-7c63-7143-b4ab-2a73b5af844f}\libusb_device.inf
libwdi:debug [syslog] !!!  sto:                Failed to import driver package into Driver Store. Error = 0x00000002
```

Thank your for this project.

**Comment by pbatard** [comment]
Thanks for the report. This is now fixed in the latest source.

For the record, this should only happen if you create your own custom version of libwdi and choose to embed libusb-win32 but not libusbK. You should also know that, because the libusb-win32 driver is included in libusbK, most people choose to get libusb-win32 driver from libusbK rather than the standalone version, especially as it also allows them to choose between `libusb0.sys` (which is being obsoleted) and `libusbk.sys`.
